layout_spectrum: 0.6264447917168646
typography_spectrum: 0.049824018508177435
color:
  brandStrength: 0.6352492388127612
  lightness: 0.10511988743420432
  saturation: 0.49223286748209066
  rhythmicContrast: 0.058175745733211395
  brandColors:
    - '#FF8000'
    - '#FFD933'
    - '#CCCC52'
    - '#8FB359'
    - '#192B33'
logo: null
name: LØBEMENTOR
url: 'http://lobementor.com'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/37433af0-c83f-4685-9611-ce66ca3ebb5d.png
title: LØBEMENTOR
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/d6942d1a-c3ff-4356-ae15-bf9e5f19826a.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/d6942d1a-c3ff-4356-ae15-bf9e5f19826a.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/db3375a3-90be-45ab-a427-90095b80a12c.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/db3375a3-90be-45ab-a427-90095b80a12c.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose:
  - type: external
    label: Book en tid
    url: 'https://jorgenlarsen.youcanbook.me'
github: true
