layout_spectrum: 0.3139142815506842
typography_spectrum: 0.07363349434827446
color:
  brandStrength: 0.2743217627571361
  lightness: 0.23758921813293554
  saturation: 0.419317358884278
  rhythmicContrast: 1
  brandColors:
    - '#F4D751'
    - '#DBAA3A'
    - '#70B9B8'
    - '#5D6067'
    - '#77968E'
logo: null
name: LØBEMENTOR
url: 'http://lobementor.com'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/37433af0-c83f-4685-9611-ce66ca3ebb5d.png
title: LØBEMENTOR
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/d6942d1a-c3ff-4356-ae15-bf9e5f19826a.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/d6942d1a-c3ff-4356-ae15-bf9e5f19826a.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/db3375a3-90be-45ab-a427-90095b80a12c.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/db3375a3-90be-45ab-a427-90095b80a12c.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose:
  - type: internal
    label: BOOKING
    item: daf2629e-cf61-4906-bb3e-3960544c19f0
  - type: contact
    url: 'mailto:jorgen@lobementor.com'
    label: Contact me
github: true
